CREATE TABLE USERS(ID BIGINT PRIMARY KEY AUTO_INCREMENT,
   LOGIN VARCHAR(255),
   PASSWORD VARCHAR(255));

CREATE TABLE URLS(ID BIGINT PRIMARY KEY AUTO_INCREMENT,
   LONGURL VARCHAR(255),
   SHORTURL VARCHAR(255));

CREATE TABLE QUERIES(ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  USERID BIGINT,
  URLID BIGINT,
  FOREIGN KEY (USERID)  REFERENCES USERS (ID),
  FOREIGN KEY (URLID)  REFERENCES URLS (ID)
);
